json-server:
  container_name: json_server
  ports:
    - "3000:80"
  volumes:
    - ./data:/data
  networks:
    - reverse_proxy
  labels:
    - traefik.backend=json_server_test
    - traefik.frontend.rule=Host:json_server.testdev.com
    - traefik.docker.network=reverse_proxy
    - traefik.port:80
  restart: always
networks:
  reverse_proxy:
    external: true
